name: 11ty build
on: [push]
jobs:
  build_deploy:
   runs-on: ubuntu-latest
   steps:
   - name: Checkout last commit of repository
     uses: actions/checkout@v3
   - name: Install 11ty and build website
     uses: extrawitz/11ty-dockerless-build@v1
   - name: Deploy
     uses: peaceiris/actions-gh-pages@v3
     with:
       publish_dir: build
       github_token: ${{ secrets.GITHUB_TOKEN }}
